### ISSUE TITLE
Where did you get the API guide?

### ISSUE THREAD

**Issue by danyhm** [kulinacs/htb#1]
Hello,
I'm trying to write an API wrapper myself, I just don't understand where did you get the API guide?
there's no official manual.

I'd be glad if you shed a light on this

**Comment by danyhm** [comment]
never mind I found out.

**Comment by Gr3atWh173** [comment]
Where did you find it?

**Comment by kulinacs** [comment]
Personally I didn't find it anywhere, I ran Burp on the website.

**Comment by Gr3atWh173** [comment]
Well thats a bummer. I spent the last hour looking for the docs 😆
